#+TITLE: Answers

* Questions

** Analysis

1. Add \( z^6 \) to both sides, and the LHS is a binomial expansion. Then take 6th roots taking care to respect roots of unity.

2. The function is not well-defined since it does not define a value for \( \mathbb{N} \in \mathcal{P}(\mathbb{N}) \) (or any other subset of the naturals with infinite cardinality).

3. ?

4. False, a counterexample is given [[https://en.wikipedia.org/wiki/Non-analytic_smooth_function#An_example_function][here]].

5. A proof is given [[https://zwurc.blogspot.com/2015/10/gamma-function-proof-that-factorial-is.html][here]].

** Algebra

1. ?

2. ?

3. ?

4. For all residues \( a \) modulo \( p \) we have \( a^p - a \equiv 0 \mod p \), hence there are no solutions in \( \mathbb{F}_p \) to \( x^p - x + 1 = 0 \) for example.  A more general result is that no finite field is algebraically closed.

5. They do form a group.  Every element has an inverse, equal to \( -x \) for all \( x \) except \( -2^{31} \) which is its own inverse (ie adding it to itself in two's complement gives 0).

** Linear Algebra

1. ?
2. Note the determinant (and thus its reciprocal) of \( M \) is necessarily in \( K \) by the leibniz formula, which is a sum of products of the entries of \( M \) (ie ops which are closed in \( M \)).  For the same reason, the adjugate of \( M \), \( adj(M) = C^T \) has all of its entries in \( K \) since the cofactor matrix \( C \) of \( M \) has entries which are determinants of matrices with entries all in \( M \).  Then the result follows from:
   
   \[
   M^{-1} = \frac{adj(M)}{det(M)}
   \]
3. False, a counterexample is:
   \[
   A = \begin{pmatrix}
      0 & 0 & 1 \\
      1 & 0 & 0 \\
      0 & 1 & 0
   \end{pmatrix}
   \]
   We might guess from this \( A \) must either be symmetric or [[https://en.wikipedia.org/wiki/Persymmetric_matrix][persymmetric]], but this is also not true:
   \[
   A = \begin{pmatrix}
      0 & 0 & 0 & 1 & 1 & 0 & 0 & 0 & 0 & 0 \\
      0 & 0 & 0 & 1 & 1 & 0 & 0 & 0 & 0 & 0 \\
      0 & 0 & 0 & 1 & 1 & 0 & 0 & 0 & 0 & 0 \\
      0 & 0 & 0 & 0 & 0 & 1 & 1 & 1 & 1 & 1 \\
      0 & 0 & 0 & 0 & 0 & 1 & 1 & 1 & 1 & 1 \\
      1 & 1 & 1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
      1 & 1 & 1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
      1 & 1 & 1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
      1 & 1 & 1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
      1 & 1 & 1 & 0 & 0 & 0 & 0 & 0 & 0 & 0
   \end{pmatrix}
   \]
   (The above also provides a counterexample to row and column sets equal \( \Rightarrow  \) row and column multisets equal)
In the case \( |R| = |C| \le 2 \) the statement (about symmetricity) is true: suppose for a contradiction the matrix is not symmetric, then there exists a row \( R_i \) and column \( C_i \) such that \( R_i \ne C_i \).  They are not equal so we must have \( R_{i,k} \ne C_{i,k} \) for some \( k \).  Then consider the kth row \( R_k \) and column \( C_k \), these must be the same since they intersect at their kth component.  But \( V = R_k = C_k \) intersects both \( C_i \) and \( R_i \) at their kth components, as this implies \( V \) has different values at a given index, a contradiction.

** Number Theory

1. If \( a \) and \( b \) are odd, then \( a^2 + b^2 \equiv 2 \mod 4 \), but all even squares are congruent to \( 0 \mod 4\).

2. Choose the primorials as the subsequence.

3. \( \pi(10000) \) + \( \pi(\lfloor \sqrt{10000} \rfloor}) \) , since if some \( p | n \), then we need to check if no other primes divide it, and also that it is not a prime power (ie \( p^2 \not | n \)).  Note if \( n = 1 \), we "ask" all primes and get "no" for everything.

4. Suppose for a contradiction there is some such sequence \( a_n \) not equal to the powers of two sequence.  Note \( a_1 = 1 \).  Let \( k \) be the smallest integer such that \( a_k \not = 2^k \). Then either \( a_k > 2^k \), in which case \( a_k -1 \) is not representable as a sum of unique terms.  Otherwise \( a_k < 2^k \) in which case \( a_k \) can be written as the sum of unique terms in more than one way.

** Graph Theory

1. Proceed by induction.

** Computation

1. Binary search

2. ??

3. ??

4. Note the return types of \( \text{append} \) and \( \text{remove} \) are both \( \text{unit} \) so in the implementation of those methods we can append the method call to a linked list and return, and then whenever \( \text{get} \) is called we iterate through the list and actually perform the appends and removals before completing the \( \text{get}  \).  Note we can also check the validity of \( \text{remove}  \)s by keeping a counter of how many elements there are in the list.

5. We're not interested in the fact that ~x~ will be changed in place by the second function since we only care about outputs.  In most cases the functions return exactly the same value, but we can use the second function to append a list to itself and get the [[https://docs.python.org/dev/library/constants.html#Ellipsis][ellipses]] of doom:
   #+begin_src python
   >>> x = y = [1]
   >>> append1(x, y)
   [1, [1]]
   >>> append2(x, y)
   [1, [...]]
   #+end_src
