#+TITLE: Answers

* Questions

** Analysis

1. Add \( z^6 \) to both sides, and the LHS is a binomial expansion. Then take 6th roots taking care to respect roots of unity.

2. The function is not well-defined since it does not define a value for \( \mathbb{N} \in \mathcal{P}(\mathbb{N}) \) (or any other subset of the naturals with infinite cardinality).

3. ?

** Algebra

1. ?

2. ?

3. ?

4. For all residues \( a \) modulo \( p \) we have \( a^p - a \equiv 0 \mod p \), hence there are no solutions in \( \mathbb{F}_p \) to \( x^p - x + 1 = 0 \) for example.

5. They do not form a group since \( -2^{31} \) does not have an inverse.

** Linear Algebra

1. ?
2. Note the determinant (and thus its reciprocal) of \( M \) is necessarily in \( K \) by the leibniz formula, which is a sum of products of the entries of \( M \) (ie ops which are closed in \( M \)).  For the same reason, the adjugate of \( M \), \( adj(M) = C^T \) has all of its entries in \( K \) since the cofactor matrix \( C \) of \( M \) has entries which are determinants of matrices with entries all in \( M \).  Then the result follows from:
   
   \[
   M^{-1} = \frac{adj(M)}{det(M)}
   \]

** Number Theory

1. If \( a \) and \( b \) are odd, then \( a^2 + b^2 \equiv 2 \mod 4 \), but all even squares are congruent to \( 0 \mod 4\).

2. Choose the primorials as the subsequence.

3. \( \pi(10000) \) + \( \pi(\lfloor \sqrt{10000} \rfloor}) \) , since if some \( p | n \), then we need to check if no other primes divide it, and also that it is not a prime power (ie \( p^2 \not | n \)).  Note if \( n = 1 \), we "ask" all primes and get "no" for everything.

4. Suppose for a contradiction there is some such sequence \( a_n \) not equal to the powers of two sequence.  Note \( a_1 = 1 \).  Let \( k \) be the smallest integer such that \( a_k \not = 2^k \). Then either \( a_k > 2^k \), in which case \( a_k -1 \) is not representable as a sum of unique terms.  Otherwise \( a_k < 2^k \) in which case \( a_k \) can be written as the sum of unique terms in more than one way.

** Graph Theory

1. Proceed by induction.

** Computation

1. Binary search

2. ??

3. ??
