#+TITLE: Answers

* Questions

** Analysis

1. Add \( z^6 \) to both sides, and the LHS is a binomial expansion. Then take 6th roots taking care to respect roots of unity.

2. The function is not well-defined since it does not define a value for \( \mathbb{N} \in \mathcal{P}(\mathbb{N}) \) (or any other subset of the naturals with infinite cardinality).

3. ?

** Algebra

1. ?

2. ?

3. ?

4. For all residues \( a \) modulo \( p \) we have \( a^p - a \equiv 0 \mod p \), hence there are no solutions in \( \mathbb{F}_p \) to \( x^p - x + 1 = 0 \) for example.

5. They do not form a group since \( -2^{31} \) does not have an inverse.

** Linear Algebra

1. ?

** Number Theory

1. If \( a \) and \( b \) are odd, then \( a^2 + b^2 \equiv 2 \mod 4 \), but all even squares are congruent to \( 0 \mod 4\).

2. Choose the primorials as the subsequence.

3. \( \pi(10000) \), since if some \( p | n \), then we need to check if no other primes divide it. Note if \( n = 1 \), we "ask" all primes and get "no" for everything.

** Graph Theory

1. Proceed by infinite descent or induction.

** Computation

1. Binary search

2. ??

3. ??
