#+TITLE: IAM

* Users and Roles

An AWS account is first associated with one root user who has complete access over AWS services and accounts.  It is [[https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html#create-iam-users][best practice]] to create an IAM user using the root user and lock away the root user credentials.

*** IAM Users
An *IAM User* consists of a name, a password for accessing the AWS console and up to two access keys that can be used with the AWS API or CLI.  It's granted permissions by either making it a member of a user group (recommended) or directly adding policies.

*** IAM Roles
An *IAM Role* is similar to an IAM user, but does not have any credentials associated with it.  An IAM user can assume a role to temporarily take on permissions for a specific task.

*** IAM Policies
An *IAM policy* describes which entities can access particular resources.  Many policies will exist by default in your account: https://us-east-1.console.aws.amazon.com/iamv2/home#/policies.

*** Principals
A principal is an individual or application which can make requests for an action on an AWS resource.  The principal is authenticated as the AWS account root user or an IAM entity (a user or role) to make requests to AWS.
