#+TITLE: Integral Domains

* Euclidean Domains

*Definition* Let \( R \) be an integral domain, then \( R \) is a Euclidean domain if there exists some function \( d: R \backslash \{0\} \to \mathbb{Z}^{\ge 0} \) which satisfies:

1. If \( a \in R, \ b \ne 0 \in R \) then \( \exists q, r \in R \) such that \( a = qb + r \) and either \( r = 0 \) or \( f(r) < f(b) \)

2. For all \( a, b \in R \ne 0 \) we have \( f(a) \le f(ab) \)

So Euclidean Domains generalise the *Division Theorem* to (commutative) rings. We will see for an integral domain, having the property that it is a Euclidean domain is a fairly strong condition.

** Examples
   
   1. The Gaussian integers \( \mathbb{Z}[i] \) are a Euclidean domain. This can be seen by taking \( d(a + bi) = |a + bi| = \sqrt{a^2 + b^2} \).

   2. Any field \( F \) is a Euclidean domain since we can take \( d(0) = 0 \) and \( d(x) = 1 \) for \( x \ne 0 \). To see this satisfies (1), given some \( a, b \in R \) we can choose \( q = ab^{-1} \) or \( q = 0 \) if \( a = 0 \), and have \( a = qb \) as required. (2) is trivially satisfied.


* Principle Ideal Domains

*Definition* Let \( R \) be an integral domain, then \( R \) is a PID if for all ideals \( I \) in \( R \exists a \in R \) such that \( I = \langle a \rangle \).

*Theorem* All Euclidean domains are *Principle Ideal Domains*.
