#+TITLE: Vector Line Integral

* Definition

Given a vector field \( F : R^n \to R^m \), and a parametric curve \( r : R \to R^n \), we define the vector line integral:

\[ \int_C F \cdot dr = \int_a^b F(r(t)) \cdot r'(t) dt \]

Intuitively, it can be thought of being a measure of how much the curve *agrees* with the vector field: at each point on the curve we are taking the dot product of the *tangent* vector and the vector defined by the vector field at that point.

We show another common notation for a vector line integral:

\begin{align}
\int_C F \cdot dr &= \int_C \langle P(x, y), \ Q(x, y) \rangle  \cdot dr = \int_C \langle P(x, y), Q(x, y) \rangle  \cdot \langle \frac{dx}{dt}, \frac{dy}{dt} \rangle \ dt \\
&= \int_C P(x, y)dx + Q(x, y)dy
\end{align}

However, note the endpoints of the curve \( C \) are given in \( t \) values, so conversion of \( x \) and \( y \) may be necessary to evaluate the integral (alternatively we can apply the Gradient theorem if \( F \) is nice enough or Green's theorem if the curve is closed).

* The Fundamental Theorem of Calculus for Line Integrals

The FTC for line integrals, also known as the *Gradient Theorem*, states that the line integral through a vector field which is the *Gradient* of some scalar function is simply that scalar function evaluated at the lines endpoints.

Ie, if \( \vec{F} : R^n \to R^n \) and \( \vec{r} : R \to R^n \), and further \( \vec{F} = \nabla G \) for some scalar function \( G:R^n \to R \), then:

\begin{align}
\int_a^b \vec{F}(r(t)) \cdot \vec{dr} &= \int_a^b \nabla G(r(t)) \cdot \vec{dr}\\
&= \int_a^b \nabla G(r(t)) \cdot r'(t) \ dt\\
&= G(b) - G(a)
\end{align}

We call vector fields which have this property *conservative*.

The proof of theorem relies on the *multivariate chain rule* from which we deduce:

\[
\frac{d}{dt} G(r(t)) = \nabla G(r(t)) \cdot r'(t)
\]

* Relation to Scalar Line Integral

Let \( \theta (t) \) denote the angle between \( F(t) \) and \( r(t) \) at \( t \), now rewriting using dot products:



\[
\int_a^b F(r(t)) \cdot r'(t) dt = \int_a^b |F(r(t))| \ |r'(t)| \cos{(\theta(t))} \ dt
\]

Now suppose \( r(t) \) is always tangent to \( F(r(t)) \), leaving \( \theta (t) = 1 \) ,for all \( t \):

\begin{align}
\int_a^b F(r(t)) \cdot r'(t) dt &= \int_a^b |F(r(t))| \ |r'(t)| \ dt \\
&= \int_a^b g(r(t)) \ |r'(t)| \ dt \\
&= \int_C g(r) ds
\end{align}

With \( g(r) = |f(r)| \). Hence we can conclude that the *scalar line integral* is just a special case of the vector line integral.

