name: ci

on:
  push:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pull
        run: docker pull silex/emacs:27.2
      - name: Run
        run: docker run emacs -v ox-yaow-publish.el:.ox-yaow-publish.el -v wiki/:wiki/ -v $(pwd):org/ "emacs --script ox-yaow-publish.el"
      - name: debug
        run: ls wiki/
