name: ci

on:
  push:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pull
        run: docker pull silex/emacs:27.2
      - name: Run
        run: docker run -v $(pwd)/wiki-html:/wiki -v $(pwd):/org silex/emacs:27.2 emacs --script /org/ox-yaow-publish.el
      - name: debug
        run: ls -la $(pwd)/wiki-html
