name: ci

on:
  push:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      EMACS_VERSION: 29.4
    steps:
      - uses: actions/checkout@v4
        with:
          # https://github.com/ad-m/github-push-action/issues/44#issuecomment-581706892
          persist-credentials: false
          fetch-depth: 0

      - name: Pull
        run: docker pull silex/emacs:${{ env.EMACS_VERSION }}

      - name: Export org Files to html
        run: docker run -v $(pwd)/wiki-html:/root/wiki -v $(pwd):/root/org silex/emacs:${{ env.EMACS_VERSION }} bash -c 'apt update && apt install git -y && emacs --script /root/org/ox-yaow-publish.el'

      - name: Clone Site Repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
          repository: LaurenceWarne/LaurenceWarne.github.io
          path: ./LaurenceWarne.github.io/

      - name: Copy Files
        run: |
          rm -rf LaurenceWarne.github.io/_wiki/*
          find $(pwd)/wiki-html/ | grep "~$" | xargs -r rm
          cp -r $(pwd)/wiki-html/* LaurenceWarne.github.io/_wiki

      - name: Set Environment
        run: echo "MSG=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

      - name: Commit
        working-directory: ./LaurenceWarne.github.io/
        run: |
          git add -A
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config user.name "GH-actions-bot"
          git commit -m "Sync from org repo: $MSG"

      # https://github.com/ad-m/github-push-action
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          directory: ./LaurenceWarne.github.io/
          github_token: ${{ secrets.GH_PAT }}
          repository: LaurenceWarne/LaurenceWarne.github.io
          branch: master
